# Generated by Django 4.0 on 2023-10-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_category_job_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'jobs'},
        ),
    ]
